#!/bin/bash

USAGE="Usage: $0 host [port]"

#error handling
if [ $# -eq 0 ]; then
	echo $USAGE
	exit 1
fi

if (( $# > 2 )); then
	echo $USAGE
	exit 1
fi

#cts6.dev.tdgroup.com
domain="http://10.154.221.97/"
path="json.php?host=$1&port=$2&csr=&s="
wget  -O $PWD/results/$1.json $domain$path

